server:
  port: 777

spring:
  datasource:
    url: jdbc:mysql://localhost/book_store?useSSL=false
    username: book_store
    password: book_store
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

crnk:
  enabled: true
  path-prefix: /api
  default-page-limit: 20
  max-page-limit: 1000
  allow-unknown-attributes: false
  return404-on-null: true

