server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/book_store
    username: book_store
    password: book_store
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

crnk:
  enabled: true
  path-prefix: /api
  default-page-limit: 20


